### ISSUE TITLE
obsluga bledow przy podlaczonym innym sockecie

### ISSUE THREAD

**Issue by roblad** [mkorz/IntegraPy#7]
Witam,

Zauwazeylem ze brak jest obslugi bledow  tu chodzi o zajetosc przez polaczenie innego programu do centrali

root /integra # python3 integrademo.py
0x10
0x42
0x75
0x73
0x79
0x21
0xD
0xA
0xD7
0x0
0x0
0x0
0x0
0x0
0x0
0x0
0x0
Traceback (most recent call last):
  File "integrademo.py", line 257, in <module>
    iVersion()
  File "integrademo.py", line 137, in iVersion
    resp = sendcommand("7E")
  File "integrademo.py", line 88, in sendcommand
    raise Exception("Wrong header - got %X%X" % (resp[0], resp[1]))
Exception: Wrong header - got 1042

**Comment by mkorz** [comment]
Thanks, indeed, the error handling is lacking. 
Unfortunately, as far as I know, Integra supports a single connection only, so options here are limited - I can inform the user and potentially retry the command.

**Comment by roblad** [comment]
Yes,

But what do yo think about arm and disarm, and connection with password and events handling "wylaczono alarm strefa...."

https://github.com/c-soft/satel_integra

http://fx-team.fulara.com/obsluga-centrali-integra-w-c-raspbian/
