### ISSUE TITLE
next error in python3.6.3

### ISSUE THREAD

**Issue by roblad** [mkorz/IntegraPy#9]
python3 -m IntegraPy.demo 192.168.100.180

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/IntegraPy/IntegraPy/demo.py", line 27, in <module>
    for part in integra.get_armed_partitions()
  File "/tmp/IntegraPy/IntegraPy/__init__.py", line 205, in get_armed_partitions
    resp = self.run_command(b'0A')
  File "/tmp/IntegraPy/IntegraPy/__init__.py", line 81, in run_command
    raise Exception('Wrong header - got {}'.format(hexlify(resp[:2])))
Exception: Wrong header - got b'1042'

**Comment by mkorz** [comment]
Thank you for reporting this, 

I tried to replicate this issue on Debian Sid:
```
python3 --version
Python 3.6.3
```
but so far with little success. 
Could you care to provide more details?
1. The version of Integra (model and firmware).
1. The version of ETHM-1 firmware.
1. The output of  `uname -a` from the machine.
1. Did it work with the lower version of Python on the same machine, or was it a different machine?

Cheers!

**Comment by roblad** [comment]
Linux raspberrypi2 4.9.63-v7+ #1052 SMP Sat Nov 18 21:50:59 GMT 2017 armv7l GNU/Linux
Ver. Centrali 1.15  INTEGRA64
ETHM-1 1.07
No lover version of python not work

**Comment by mkorz** [comment]
Thanks, I have a suspicion it might be connected to the arm architecture. I don't have a spare RPi laying around, but will try to set up test environment in QEMU and have at look at this.

**Comment by roblad** [comment]
I think that there is a responce time to short, when I try again and again it started on RPI

not armed

Model:            INTEGRA 64
Version:          1.15 2016-03-09
Time:             2017-11-19 21:40:01
Armed partitions: 
Violated zones:   
Active outputs:   Wyjście   3
-------------------------------------------------------------------------------
10 last events:
Date & time      | Code | Source
2017-11-19 21:37 |  409 | 11
2017-11-19 21:35 |  409 | 10
2017-11-19 21:34 |  1007 | 10
2017-11-19 21:32 |  409 | 11
2017-11-19 21:31 |  409 | 10
2017-11-19 21:31 |  1007 | 10
2017-11-19 18:06 |  50 | 100
2017-11-19 18:06 |  54 | 192
2017-11-19 18:06 |  19 | 0
2017-11-19 18:05 |  339 | 209


armed

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/site-packages/IntegraPy/demo.py", line 27, in <module>
    for part in integra.get_armed_partitions()
TypeError: sequence item 0: expected str instance, NameRecord found



And another linux

not armed

python3 -m IntegraPy.demo 192.168.100.180

Model:            INTEGRA 64
Version:          1.15 2016-03-09
Time:             2017-11-19 21:29:31
Armed partitions: 
Violated zones:   
Active outputs:   Wyjście   3
-------------------------------------------------------------------------------
10 last events:
Date & time      | Code | Source
2017-11-19 18:06 |  50 | 100
2017-11-19 18:06 |  54 | 192
2017-11-19 18:06 |  19 | 0
2017-11-19 18:05 |  339 | 209
2017-11-19 18:05 |  50 | 100
2017-11-19 18:05 |  54 | 192
2017-11-19 18:05 |  1022 | 5
2017-11-19 18:04 |  50 | 100
2017-11-19 18:04 |  54 | 192
2017-11-19 18:04 |  19 | 0



 python3 --version
Python 3.7.0a1


uname -a
Linux  4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

armed

python3 -m IntegraPy.demo 192.168.100.180
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/site-packages/IntegraPy/demo.py", line 27, in <module>
    for part in integra.get_armed_partitions()
TypeError: sequence item 0: expected str instance, NameRecord found

**Comment by roblad** [comment]
python3 -m IntegraPy.constants 192.168.100.180
/usr/local/lib/python3.6/runpy.py:125: RuntimeWarning: 'IntegraPy.constants' found in sys.modules after import of package 'IntegraPy', but prior to execution of 'IntegraPy.constants'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))

**Comment by s53zo** [comment]
Did you manage to solve armed / not armed problem? I get the same error:

TypeError: sequence item 0: expected str instance, NameRecord found

Can anybody provide a solution please?

**Comment by mkorz** [comment]
Hello @s53zo,

Could you please try the current version and let me know if it works for you?
Thanks!

**Comment by s53zo** [comment]
All is OK now, thanks!
